name: Demo Build CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: demo-xxx
          path: ${{ github.workspace }}/build/
